### ISSUE TITLE
Hero Section, left side

### ISSUE THREAD

**Issue by fardinzam** [acm-ucr/gardening-website#3]
- don't worry about the whole section, just make the title text, "Welcome to UCR Gardening!"
- work on the file under src/components/home/Hero.jsx
<img width="877" alt="Screenshot 2024-06-28 at 10 56 22 AM" src="https://github.com/acm-ucr/ucrgardening/assets/55073341/db5c7072-40ca-44b7-8224-3352733be479">

**Comment by devansh-dek** [comment]
Is this issue open? Can i work on it?
