### ISSUE TITLE
Join Gardening text

### ISSUE THREAD

**Issue by fardinzam** [acm-ucr/gardening-website#5]
- Create the title and paragraph text
- make button 
- work on filer src/components/home/Join.jsx
<img width="877" alt="Screenshot 2024-06-28 at 11 13 06 AM" src="https://github.com/acm-ucr/ucrgardening/assets/55073341/1dbd6f65-1e2e-46d7-a550-92d8dd3dda6b">

**Comment by MicahBala** [comment]
@fardinzam Can you assign me this project. This is my first time ever contributing to any open source. Than you.

**Comment by fardinzam** [comment]
> @fardinzam Can you assign me this project. This is my first time ever contributing to any open source. Thank you.

Hello @MicahBala , unfortunately this project is only for ACM@UCR members that applied for a SWE position. Apologies for the confusion
